name: 'Bug report'
description: 'File a bug report'

labels:
  - 'bug'

body:
  - type: 'markdown'
    attributes:
      value: 'Thank you for filing a bug report. Please complete the form below so we can triage, reproduce, and fix your issue.'

  - id: 'tldr'
    type: 'textarea'
    attributes:
      label: 'TL;DR'
      description: 'Describe the bug in 1-2 sentences.'
    validations:
      required: false

  - id: 'expected_behavior'
    type: 'textarea'
    attributes:
      label: 'Expected behavior'
      description: 'What did you expect to happen?'
    validations:
      required: true

  - id: 'observed_behavior'
    type: 'textarea'
    attributes:
      label: 'Observed behavior'
      description: 'What happened instead?'

  - id: 'version'
    type: 'input'
    attributes:
      label: 'Version'
      description: 'What version are you running? (legitify version)'
    validations:
      required: true

  - id: 'os'
    type: 'dropdown'
    attributes:
      label: 'On which operating system are you using legitify?'
      options:
        - 'Linux'
        - 'Mac OS'
        - 'Windows'
        - 'Other (please elaborate in the description)'
    validations:
      required: true

  - id: 'logs'
    type: 'textarea'
    attributes:
      label: 'Relevant log output'
      description: 'Please copy and paste any relevant log output. This will be automatically formatted into code block, so no need for backticks.'
      render: 'text'

  - id: 'additional'
    type: 'textarea'
    attributes:
      label: 'Additional information'
      description: 'Is there anything else you think we should know?'
